#Deployment
apiVersion: apps/v1
kind: Deployment
metadata:
  # ชื่อ Deployment
  name: consumer-deployment
spec:
  selector:
    matchLabels:
    # ชื่อ app
      app:  consumer
  replicas: 1
  template:
    metadata:
      labels:
        app: consumer
    spec:
      containers:
        - name: consumer
          image: consumer:1.0
          ports:
          - containerPort: 8082
