version: '3.9'

services:
  zookeeper:
    image: wurstmeister/zookeeper
    restart: always
    ports:
      - 2181:2181

  kafka:
    image: wurstmeister/kafka
    restart: always
    ports:
      - 9092:9092
    depends_on:
      - zookeeper
    links:
      - zookeeper:zookeeper
    environment:
      KAFKA_ADVERTISED_HOST_NAME: kafka
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181

  consumer:
    build:
      context: consumer
    restart: always
    ports:
      - 8082:8082
    depends_on:
      - kafka
    links:
      - kafka:kafka

  producer:
    build:
      context: producer
    restart: always
    ports:
      - 8081:8081
    depends_on:
      - kafka
    links:
      - kafka:kafka

