#Deployment
apiVersion: apps/v1
kind: Deployment
metadata:
  # ชื่อ Deployment
  name: kafka-deployment
spec:
  selector:
    matchLabels:
    # ชื่อ app
      app:  kafka
  replicas: 1
  template:
    metadata:
      labels:
        app: kafka
    spec:
      containers:
        - name: kafka
          image: wurstmeister/kafka
          ports:
          - containerPort: 9092
          env:
          - name: KAFKA_ADVERTISED_HOST_NAME
            value: kafka
          - name: KAFKA_ZOOKEEPER_CONNECT
            value: zookeeper:2181
