#Deployment
apiVersion: apps/v1
kind: Deployment
metadata:
  # ชื่อ Deployment
  name: zookeeper-deployment
spec:
  selector:
    matchLabels:
    # ชื่อ app
      app:  zookeeper
  replicas: 1
  template:
    metadata:
      labels:
        app: zookeeper
    spec:
      containers:
        - name: zookeeper
          image: wurstmeister/zookeeper
          ports:
          - containerPort: 2181

