apiVersion: apps/v1 # for versions before 1.9.0 use apps/v1beta2
kind: Deployment
metadata:
  name: hello-kube-deployment
spec:
  selector:
    matchLabels:
      app: hello-kube
  replicas: 3
  template:
    metadata:
      labels:
        app: hello-kube
    spec:
      containers:
      - name: hello-kube
        image: johnr46/hello-kube:1.0
        ports:
        - containerPort: 80
        

