apiVersion: v1
kind: Service
metadata:
  name: kafka-service
  # ชื่อแอปที่จะ expose ด้วย service นี้
  labels:
    name: kafka
spec:
  ports:
  - name: kafka-port
    port: 9092
  # ชื่อแอปที่จะ expose ด้วย service นี้
  selector: 
    app: kafka
  type: LoadBalancer
