apiVersion: v1
kind: Pod
metadata:
  name: hello-kube
  labels: 
    app: hello-kube
spec:
  containers:
    - image: johnr46/hello-kube:1.0
      name: hello-kube
      ports:
        - containerPort: 80

